### ISSUE TITLE
"/" in "code" field makes deleting/editing impossible

### ISSUE THREAD

**Issue by dampfkadse** [patrick246/shortlink#1]
if you put a "/" in the "code" field you can't delete or edit this shortlink anymore

**Comment by patrick246** [comment]
Fixed by 1.1.2. You can't add any non-path-safe characters to codes anymore, all codes that contain them will be removed. Check the logs once you update, as this will show you the codes and destinations that have been deleted

**Comment by patrick246** [comment]
Fixed by 1.1.2. You can't add any non-path-safe characters to codes anymore, all codes that contain them will be removed. Check the logs once you update, as this will show you the codes and destinations that have been deleted
